### ISSUE TITLE
All is very slow

### ISSUE THREAD

**Issue by galek** [faha223/PhysicsEngine#1]
Hi

I implemented your sample,and can say what all works is very slow.

VS profiler says what i have conflict of resources with default physx thread.

**Comment by faha223** [comment]
I have stopped developing this. I should probably update the readme to mention this, but I haven't touched this code in well over a year. If you want to use this for anything you're welcome to, but if I start to write anything similar in the future, I'll likely be starting from scratch.

**Comment by galek** [comment]
Ok, i'm already fixed this.
my current problem-thread synchronization.

I used this_thread::sleep(time of running update), so maybe exist many correct solution?
